### ISSUE TITLE
plotPhylonet to make hybrid edge for small gamma better

### ISSUE THREAD

**Issue by crsl4** [crsl4/PhyloNetworks.jl#12]
if gamma is too small, the hybrid edge sometimes does not appear on the plot. Maybe include a threshold for the smallest gamma, or even, change to dotted line if gamma is below the threshold.

**Comment by crsl4** [comment]
also good idea if the major hybrid edge were black and looked more like a "tree edge", it would make the plot much easier to interpret. varying the color/width of the minor hybrid edge depending on gamma is also another good idea

**Comment by crsl4** [comment]
Do we want tree edges to be thicker depending on bootstrap support value?

**Comment by cecileane** [comment]
perhaps there could be an option for the tree edge width, so that the user can decide on his/her own based on bootstrap values, his/her preferred threshold on bootstrap values, or separate things like gain/loss of a character, etc. An option to show the (tree) edge indices on the plot, and an option to input a vector of (tree) edge widths would give a lot of flexibility, beyond bootstrap values.

**Comment by cecileane** [comment]
will close: plotting functions have been moved to [PhyloPlots](https://github.com/cecileane/PhyloPlots.jl) and the edge with attributes could be modified with R, if the R-based function is used. Might need more work, but much easier with the new functions, and low priority.
