### ISSUE TITLE
wrong warning readTableCF

### ISSUE THREAD

**Issue by crsl4** [crsl4/PhyloNetworks.jl#120]
I am reading a table produced by `readTrees2CF` and I get a warning that the column names do not match, when they do.
I will come back to debug this, but I don't have time right now, and wanted to document it.

```
julia> cf = readTableCF("1_astral_cf.txt")
┌ Warning: Column names for quartet concordance factors (CFs) were not recognized.
│ Was expecting CF12_34, CF13_24 and CF14_23 for the columns with CF values,
│ or CF12.34 or obsCF12, etc.
│ Will assume that the first 4 columns give the taxon names, and that columns 5-7 give the CFs.
└ @ PhyloNetworks ~/.julia/packages/PhyloNetworks/zeoh2/src/readData.jl:115
Object DataCF
number of quartets: 15


shell> head 1_astral_cf.txt
t1,t2,t3,t4,CF12_34,CF13_24,CF14_23,ngenes
1,2,3,4,1.0,0.0,0.0,30.0
1,2,3,5,1.0,0.0,0.0,30.0
1,2,3,6,1.0,0.0,0.0,30.0
1,2,4,5,1.0,0.0,0.0,30.0
1,2,4,6,1.0,0.0,0.0,30.0
1,2,5,6,1.0,0.0,0.0,30.0
1,3,4,5,0.0,0.13333333333333333,0.8666666666666667,30.0
1,3,4,6,0.0,0.13333333333333333,0.8666666666666667,30.0
1,3,5,6,0.5333333333333333,0.13333333333333333,0.3333333333333333,30.0
```

**Comment by cecileane** [comment]
I think this is due to an update to `DataFrames`. What version of DataFrames do you use? Can you try pinning DataFrames to 0.20 and see if the error goes away?

Fixing this is on my to-do list. `names` returns a vector of Strings with DataFrames 0.21. It used to return a vector of Symbols. We need to change `DataFrames.names` to `DataFrames.propertynames`.

For now, the master version of PhyloNetworks has upper bounds for all dependencies, in [Project.toml](https://github.com/crsl4/PhyloNetworks.jl/blob/master/Project.toml). We will need to have these upper bounds anyway, for registering the next version.

**Comment by crsl4** [comment]
Agh! For some reason, I missed your reply, and since this error, I updated Julia and PhyloNetworks, so I don't know which version of DataFrames I was using. I do not get this warning anymore with Julia 1.4.2 and PhyloNetworks v0.11.0#master. 
I am happy to close this issue, but we can leave it open if you prefer since you mention you have something in your to-do list

**Comment by cecileane** [comment]
Let's close this. There are 3 PRs in the queue, and then I'll take care of updating the package to work with the most recent version of DataFrames. In any case:
- the master version of PhyloNetworks is fine, since upper bounds are in `Project.toml`, regardless of whether we update the package.
- the registered version is still causing issues for users (no upper bounds), but we can't register a new version until the current work in progress is in a better shape.
