### ISSUE TITLE
improve writeTopology

### ISSUE THREAD

**Issue by crsl4** [crsl4/PhyloNetworks.jl#15]
currently writeTopology only writes to screen, add the option to write to a file (and the possibility to append to the file)

**Comment by cecileane** [comment]
3 thoughts related to writeTopology and branch lengths:

- in readTopology, could missing branch lengths be given the arbitrary value of -1.0 instead of 1.0, to make it clear later that any negative value is arbitrary and should not be used? 
- in writeTopology, could branch lengths with negative values be skipped, to suppress the writing of these branches?
- could snaq also assign -1.0 to branch lengths that are not identifiable, perhaps simply for the last output network? That way, the user would know which branches have been optimized (because they would be written to the output network by writeTopology)? They would also know that missing branch lengths are simply those that are not identifiable.

**Comment by crsl4** [comment]
I do not know if it is good idea to change default to -1.0, because if a tree is read as starting topology and no branch lengths are updated to the observed CF values, then the starting tree will have branch lengths of -1.0 to start the search.
The step of updating branch lengths to match average obsCF is done outside of snaq to allow for the possibility of the user himself choosing the branch lengths where to start the search (instead of always forcing to use the obsCF). We could modify this by adding an argument "updateBL", but we would need a new layer of check if the user inputs a tree without BL (all -1.0) and chooses updateBL=false to verify that BL are not -1.0 to start the search.

**Comment by cecileane** [comment]
Good point. Then I think that it would be best for snaq to check the branch lengths of the starting tree. If all branches are >= 0, then good. If one or more branch length is -1.0, snaq could either change any -1.0 into +1.0 for branch lengths that are actually identifiable (leave the other ones at -1.0 perhaps, like external branch lengths). Or instead, snaq could pass the tree through the function that updates all branch lengths (not just those equal to -1.0) to match the observed CFs, with a warning for the user that one or more branch lengths were missing, so all were updated. 

The readTopology function could have so many more uses than reading a starting tree for snaq. I think that the information on which branch lengths are available or not should be kept. Julia is not good with NAs, but using negative values could do the trick. Then you could use the test of >=0 versus -1.0 values to make decisions in other functions.

**Comment by cecileane** [comment]
all done
