### ISSUE TITLE
hybridBootstrapSupport error

### ISSUE THREAD

**Issue by smallfishcui** [crsl4/PhyloNetworks.jl#154]
Hi there,

I am using phylonetworks to test the direction of gene flow. I have obtained the bootstrap networks, and the hybrid network, and I wrote the command like this:
#hybrid network, with 2 hybrid edges
net2=readSnaqNetwork("net2_500quar_all_finerad.out")
#bootstrap
bootnet = readMultiTopology("net2_bootstrap.out")
BSn,BSe,BSc,BSgam,BSedgenum=hybridBootstrapSupport(bootnet,net2);

But I always get the error message 
ERROR: MethodError: no method matching &(::Array{Bool,1}, ::Array{Bool,1})
Closest candidates are:
  &(::Any, ::Any, ::Any, ::Any...) at operators.jl:538
Stacktrace:
 [1] hybridBootstrapSupport(::Array{HybridNetwork,1}, ::HybridNetwork; rooted::Bool) at /projappl/project_2001259/packages/PhyloNetworks/zeoh2/src/bootstrap.jl:698
 [2] hybridBootstrapSupport(::Array{HybridNetwork,1}, ::HybridNetwork) at /projappl/project_2001259/packages/PhyloNetworks/zeoh2/src/bootstrap.jl:626
 [3] top-level scope at REPL[5]:1

Can anyone help with this? I have been using julia 1.3 and 1.5.0 and they showed the same error message. 

Thanks,
Cui

**Comment by crsl4** [comment]
Are you using the latest version of PhyloNetworks?

**Comment by cecileane** [comment]
I pushed a fix on the master branch of PhyloNetworks. Would you mind updating your project to use the latest version of the package, and see if that works for you? To do this, use these commands within julia:
```julia
julia> ; # to switch to pkg mode
pkg> add PhyloNetworks#master
pkg> status # to check which version of PhyloNetworks your project is using
```
The output of this status should show something like this:

    [33ad39ac] PhyloNetworks v0.12.0 `https://github.com/crsl4/PhyloNetworks.jl.git#master`

Then quit julia, and re-open again, to make sure that the new version is re-compiled and used.
Please let me know if the fix doesn't work.

**Comment by cecileane** [comment]
by the way, to go back and track the last registered version of the package (after we release a new version that has this fix), you can do this (in pkg mode):
```julia
pkg> free PhyloNetworks
```

**Comment by smallfishcui** [comment]
Hi cecileane,
Thanks for the fast answer. You are right, my phylonetwork package is not up to date. But I use pkg add to install this package for several times, and only version 1.11 can be installed. Does this matter with julia versions?  And in my case, I have to type ] to get the pkg mode.

Thanks,
Cui

**Comment by cecileane** [comment]
Ah yes, duh of course it's `]` to get the package mode, my apologies.
Could you also possibly use the master version of PhyloPlots? The latest registered version of PhyloPlots might be holding back the version of some dependencies, and therefore holding back PhyloNetworks. Butt the master version of PhyloPlots is has been updated to handle later versions of dependencies. It would look like this, in pkg mode:

```julia
update # to update all packages in general, if you want to do this
add PhyloPlots#master
add PhyloNetworks#master
status
```

Does that work to get you the master version of PhyloNetworks?

**Comment by smallfishcui** [comment]
No, I updated everything and the PhyloPlot, but the installation of PhyloNetworks showed another error message-add PhyloNetworks:
ERROR: Did not find a git repository at `PhyloNetworks`
 status
Status `/environments/v1.5/Project.toml`
  [336ed68f] CSV v0.6.1
  [159f3aea] Cairo v1.0.5
  [a93c6f00] DataFrames v0.20.2
  [186bb1d3] Fontconfig v0.4.0
  [c91e804a] Gadfly v1.2.1
  [33ad39ac] PhyloNetworks v0.11.0
  [c0d5b6db] PhyloPlots v0.2.2 `https://github.com/cecileane/PhyloPlots.jl.git#master`
  [91a5bcdd] Plots v1.10.1
  [6f49c342] RCall v0.13.6

I am installing it on the server, I am wondering is there something uncompatible there...

Thanks,
Cui

**Comment by cecileane** [comment]
PhyloNetworks v0.12 is not compatible with DataFrames v0.20 or earlier. So can you try updating DataFrames to v0.21 or v0.22? If you can't, it's that another package you use is holding DataFrames back to v0.20. Gadfly v0.2.1 also isn't compatible with DataFrames v0.21 or higher. You would need Gadfly v0.3 to get DataFrames v0.21 or 0.22. If you don't need these packages directly (like Fontconfig, Cairo, Gadfly, perhaps RCall), could you remove them with `rm Fontconfig` etc., then `update` all packages, until you get an update for `DataFrames`? Then the update for `PhyloNetworks` should work: to get v0.12 at least, and then you can re-try to get the master version.

I don't think it's a server issue, because your julia packages are installed into your home repository by default: not server-wide.

When you "remove" a package in `pkg` mode, you don't actually remove any downloaded file: you just tell julia that your project doesn't require a given package. If you `add` it again, it's very quick because all the package files have already been downloaded (unless Julia sees that a new version is available, compatible with the other package you want to use, and downloads it).

Make sure you quit Julia and re-open it after you have the versions you want.

I can't help with the error `Did not find a git repository` because I can't reproduce it. Could it be a typo, perhaps? In any case, the first issue here is to get an update for many different packages, like `DataFrames` etc.

**Comment by smallfishcui** [comment]
Hi Cecile, 

thanks for this detailed explanation! This is so friendly for the green hand to use julia. I tried your suggestions, by removing all the packages that were loaded, and I also deleted them from the project folder. In the end I only install PhyloNetwork, and it was updated to the PhyloNetworks v0.12.0. However, whenever I install PhyloPlots, the PhyloNetworks  automatically go down to v0.11.0, although I update the packages after the installation. What version of PhyloPlots is the newest, I have PhyloPlots v0.2.2, is that the newest?

Thanks,
Cui

**Comment by smallfishcui** [comment]
Oh I am sorry it's my bad. I thought, the hashtag is a comment, so I just ignored it...apparently julia commands are so different from linux. So I removed all the packages and installed these two packages using the command you gave above:

update # to update all packages in general, if you want to do this
add PhyloPlots#master
add PhyloNetworks#master
status

And it works! I got the 
Status `~/.julia/environments/v1.5/Project.toml`
  [33ad39ac] PhyloNetworks v0.12.0 `https://github.com/crsl4/PhyloNetworks.jl.git#master`
  [c0d5b6db] PhyloPlots v0.2.2 `https://github.com/cecileane/PhyloPlots.jl.git#master`

Thanks a lot!
Cui

**Comment by cecileane** [comment]
yeah!!

Yes, `#` is for comments in julia, in general, thank goodness. I know of only 1 exception, in package mode to ask for a specific "branch" of a package, in which case the syntax is `packagename#branchname` with no spaces around the `#`. But otherwise, `#` is indeed for comments...

Well, so let me know if the fix didn't work for you. I hope you get those bootstrap values!

**Comment by smallfishcui** [comment]
Hi Cecile,

Thanks, great to know this little tricks! Yes I get the bootstrap value now, the only problem is the bootstrap process is quite slow, so I only run 10 bootstraps, which I dont know if it gives enough information. Is it okay to run bootstrap analyses for 10 independent runs and then combine them in to the same file for later analyses? Could you please help to check, does this picture mean that there is 37.3percent of C genome comes from D, and 26.5percent of G genome comes from A?
![net2_bootstrap](https://user-images.githubusercontent.com/41078885/104716252-57eb0980-5730-11eb-91f3-5d81d81b8805.jpg)

Thanks,
Cui

**Comment by cecileane** [comment]
I can't help with interpretation without knowing what the numbers represent. I suspect that the blue numbers are estimated γ values from the original data (not the bootstrapped data). In that case, your interpretation is correct.

For the bootstrap analysis: yes it's absolutely okay to run another set of 10 (or more) runs, and later combine these new bootstrap runs with the previous 10 runs that you already have, to get a single set of bootstrap values. To make sure that the new runs are independent from the old ones, make sure to pick a new seed.

**Comment by smallfishcui** [comment]
Thanks Cecile! Yes, those are gamma values. I still have some questions
with regard to the bootstrap support and gene flow direction, but I will
open another discussion thread in the Phylonetwork google group.
Thank you very much for your help!
Cui

Cécile Ané <notifications@github.com> 于2021年1月16日周六 上午12:29写道：
