### ISSUE TITLE
infinite loop in `readTopologyLevel1`

### ISSUE THREAD

**Issue by NathanKolbow** [crsl4/PhyloNetworks.jl#201]
The code gives a couple of warnings and then never terminates.

```julia
using PhyloNetworks
readTopologyLevel1("((t9,((((t6,(t7,t3)),t5),((t8,t2),t4)))#H12:::0.5218583979),#H12:::0.4781416021);")

┌ Warning: the two edges [16, 17] attached to node -2 must be tree edges to delete node
└ @ PhyloNetworks C:\Users\Nathan\.julia\packages\PhyloNetworks\Upx5A\src\auxiliary.jl:701
┌ Warning: current hybrid 9 conflicts with previous hybrid by intersecting cycles: true, nonidentifiable topology: false, empty space for contain root: false, or does not create a cycle (probably problem with the root placement): false.
└ @ PhyloNetworks C:\Users\Nathan\.julia\packages\PhyloNetworks\Upx5A\src\readwrite.jl:868
```

**Comment by cecileane** [comment]
I don't have a solution or diagnostic, but I'm showing here what this network looks like and note that `readTopology` reads this network just fine:
```julia
julia>  using PhyloNetworks, PhyloPlots

julia> net = readTopology("((t9,((((t6,(t7,t3)),t5),((t8,t2),t4)))#H12:::0.5218583979),#H12:::0.4781416021);")
HybridNetwork, Rooted Network
17 edges
17 nodes: 8 tips, 1 hybrid nodes, 8 internal tree nodes.
tip labels: t9, t6, t7, t3, ...
((t9,((((t6,(t7,t3)),t5),((t8,t2),t4)))#H12:::0.522),#H12:::0.478);

julia> plot(net, showgamma=true);
```
<img width="480" alt="net_issue201" src="https://github.com/crsl4/PhyloNetworks.jl/assets/9857294/ecf56f33-8770-4da8-bf98-71ce51461675">

**Comment by cecileane** [comment]
Also, the problem seems to be having a hybrid edge incident to the root, which `readTopologyLevel1` wants to suppress. If we add an extra outgroup taxon to force the root to be incident to tree edges only, then the error goes away:
```julia
julia> netstring = "(((t9,((((t6,(t7,t3)),t5),((t8,t2),t4)))#H12:::0.5218583979),#H12:::0.4781416021),out);";

julia> net = readTopology(netstring)
HybridNetwork, Rooted Network
19 edges
19 nodes: 9 tips, 1 hybrid nodes, 9 internal tree nodes.
tip labels: t9, t6, t7, t3, ...
(((t9,((((t6,(t7,t3)),t5),((t8,t2),t4)))#H12:::0.522),#H12:::0.478),out);

julia> net1 = readTopologyLevel1(netstring)
HybridNetwork, Un-rooted Network
18 edges
18 nodes: 9 tips, 1 hybrid nodes, 8 internal tree nodes.
tip labels: t9, t6, t7, t3, ...
(t9:1.0,((((t6:1.0,(t7:1.0,t3:1.0):1.0):1.0,t5:1.0):1.0,((t8:1.0,t2:1.0):1.0,t4:1.0):1.0):1.0)#H12:1.0::0.522,(#H12:1.0::0.478,out:1.0):1.0);
```
<img width="915" alt="issue201_net_out" src="https://github.com/crsl4/PhyloNetworks.jl/assets/9857294/6130c64d-7f5b-4e13-a0bd-9c117488a113">

**Comment by cecileane** [comment]
To fix this, I added an error in `updateGammaz!` for a cycle of `k<=2` edges [here](https://github.com/crsl4/PhyloNetworks.jl/blame/f46226c6147f36452c39e669937d907b2ff11155/src/update.jl#L189), instead of ignoring the problem (the function simply did `return false, []` previously).

Now I wonder if ignoring the problem was "intentional" within `snaq!`, based on [this error](https://groups.google.com/g/phylonetworks-users/c/jyuBcUL_9S8/m/EvGs0PNIAAAJ). @crsl4 could you please advise? Are these 2-cycles not prevented earlier within `snaq!`?

**Comment by crsl4** [comment]
I think `updateGammaz` is not necessarily run after `proposedTop!`, so it is probably checking for non-identifiable cases (not assume there are not any).

**Comment by crsl4** [comment]
Yes, I think this function should not return an error because it is just identifying "bad" cases, but not stopping if there are 2-cycles or even bad triangles.

**Comment by cecileane** [comment]
If 2-cycles are prevented earlier within `snaq!`, then I don't see the advantage of letting `updateGammaz` ignore 2-cycles. If we let `updateGammaz` ignore 2-cycles, then:
1. the issue reported here (of an infinite loop in `readTopologyLevel1`) would come back
2. we would not fix the 2-cycle bug in `snaq!` because this bug appears, as a segmentation fault, using PhyloNetworks v0.16.2 in which `updateGammaz` ignore 2-cycles.

**Comment by crsl4** [comment]
I think `updateGammaz` is also used in the functions that only optimize branch lengths (outside `snaq!`). It might also be used within an extracted `QuartetNet`. My concern is that I would have put an error if a 2-cycle was not supposed to be there. There was a reason for this function to ignore it (that I might know if I had brought my iPad).
But I agree that just switching back is not a solution, but I want to understand why a 2-cycle was not a reason to stop there.

In parallel, I want to understand why there is a 2-cycle inside `snaq!`, but I think there are two separate things (1. why `updateGammaz` should ignore 2-cycles (or not); 2. why there was a 2-cycle in the error corresponding to the version v0.16.2) bc I think `updateGammaz!` is used beyond just a `HybridNetworks` proposed within `snaq!`. I might be wrong.

For the second case, I think one option to debug is to switch `CHECKNET=true` to stop the process when a network has a 2-cycle (and `updataGammaz` could continue to ignore 2-cycles).

For the first case (`updateGammaz` behavior), I need to find my notes first, but I am happy with any temporary fix you want to do.
