### ISSUE TITLE
MrBayer error

### ISSUE THREAD

**Issue by tsm-tsm** [crsl4/PhyloNetworks.jl#208]
Hello！ thank you for creating this platform. 
I have encountered some issues and hope to receive your assistance.

 `nohup perl /home/ug1297/mrbayes/data_results/scripts/mb.pl nexus.tar.gz -m mbblock.txt -o mb-output >&mrbayer.log&`

`cat mbblock.txt`
begin mrbayes;
set nowarnings=yes;
set autoclose=yes;
lset nst=6 rates=invgamma;
mcmcp ngen=100000 burninfrac=.25 samplefreq=50 printfreq=10000 [increase these for real]
diagnfreq=10000 nruns=3 nchains=3 temp=0.40 swapfreq=10;       [increase for real analysis]mcmc;
sumt;
end;

#####################
nohup: ignoring input

Script was called as follows:
perl mb.pl nexus.tar.gz -m mbblock.txt -o mb-output

Appending MrBayes block to each gene... done.

Job server successfully created.
Argument "^B\0M-^S<D6>^?\0\0^A\0\0\0\0\0\0\0\0" isn't numeric in numeric eq (==) at /home/ug1297/mrbayes/data_results/scripts/mb.pl line 341.
readline() on unopened filehandle at /home/ug1297/mrbayes/data_results/scripts/mb.pl line 348.

  Analyses complete:     0/22185.^MArgument "^B\0M-^S<E2>^?\0\0^A\0\0\0\0\0\0\0\0" isn't numeric in numeric eq (==) at /home/ug1297/mrbayes/data_results/scripts/mb.pl line 341, <GEN1> line 1.
readline() on unopened filehandle at /home/ug1297/mrbayes/data_results/scripts/mb.pl line 348.
Argument "^B\0M-^S<EC>^?\0\0^A\0\0\0\0\0\0\0\0" isn't numeric in numeric eq (==) at /home/ug1297/mrbayes/data_results/scripts/mb.pl line 341, <GEN2> line 1.
readline() on unopened filehandle at /home/ug1297/mrbayes/data_results/scripts/mb.pl line 348.
Argument "^B\0M-^S<F8>^?\0\0^A\0\0\0\0\0\0\0\0" isn't numeric in numeric eq (==) at /home/ug1297/mrbayes/data_results/scripts/mb.pl line 341, <GEN3> line 1.
readline() on unopened filehandle at /home/ug1297/mrbayes/data_results/scripts/mb.pl line 348.
Argument "^B\0M-^T^F^?\0\0^A\0\0\0\0\0\0\0\0" isn't numeric in numeric eq (==) at /home/ug1297/mrbayes/data_results/scripts/mb.pl line 341, <GEN4> line 1.
readline() on unopened filehandle at /home/ug1297/mrbayes/data_results/scripts/mb.pl line 348.
  Analyses complete:     1/22185.^MArgument "^B\0M-^T\n^?\0\0^A\0\0\0\0\0\0\0\0" isn't numeric in numeric eq (==) at /home/ug1297/mrbayes/data_results/scripts/mb.pl line 341, <GEN5> line 1.
readline() on unopened filehandle at /home/ug1297/mrbayes/data_results/scripts/mb.pl line 348.

**Comment by cecileane** [comment]
No idea!

But you should look into the files that were created, because the messages say that some of the steps ran successfully. For example, the script was able to create the input MrBayes: `Appending MrBayes block to each gene... done.` Also, the script seems to have detected the number of loci: `Analyses complete: 0/22185`.

The problem seems to occur when the script wants to run MrBayes on each locus: none of them (0) were successful. So the remainder of the script has issues of course, because there's no output MrBayes to use for the downstream analyses.

You should dig into your files, to find out how far exactly the script went, and where the error occurred. That's the first step to diagnose the error.

**Comment by tsm-tsm** [comment]
ug1297@gs73:~/mrbayes$ perl /home/ug1297/mrbayes/data_results/scripts/mb.pl ./data_results/baseline.gamma0.3_n30/input/1_seqgen.tar.gz -m mbblock.txt -o mb-output-data
Script was called as follows:
perl mb.pl ./data_results/baseline.gamma0.3_n30/input/1_seqgen.tar.gz -m mbblock.txt -o mb-output-data
Appending MrBayes block to each gene... done.
Job server successfully created.
Analyses complete: 30/30.
All connections closed.
Total execution time: 8 seconds.

`ug1297@gs73:~/mrbayes$ perl /home/ug1297/mrbayes/data_results/scripts/mb.pl ./data_results/baseline.gamma0.3_n30/input/1_seqgen.tar.gz -m mbblock.txt -o mb-output-data
Script was called as follows:
perl mb.pl ./data_results/baseline.gamma0.3_n30/input/1_seqgen.tar.gz -m mbblock.txt -o mb-output-data
Appending MrBayes block to each gene... done.
Job server successfully created.
Analyses complete: 30/30.
All connections closed.
Total execution time: 8 seconds.`

**Comment by cecileane** [comment]
I do not quite understand what you are doing.
1. Most of the commands and output that you showed seem to be from replicating an analysis from this [tutorial](https://github.com/crsl4/PhyloNetworks.jl/wiki/TICR:-from-alignments-to-quartet-concordance-factors), on the data from folder `data_results/baseline.gamma0.3_n30/`.
2. The analysis seems to have been successful, based on the screen message `Analyses complete: 30/30.`. Indeed, that data had only 30 loci.
3. However, you then mention a different data set, named `loci1.nexus`. I don't see any error on that other data set, so I cannot help.

So: the error you had earlier may be due to a problem with your data, because you managed to run analysis of the tutorial data successfully.

Perhaps have file names ending with `.nexus` might be an issue. The standard extension is `.nex`, not `.nexus`. But that's just a very uncertain guess.
