### ISSUE TITLE
Minor hybrid edges and edge weights

### ISSUE THREAD

**Issue by KlausVigo** [crsl4/PhyloNetworks.jl#52]
Hi @crsl4, 
Minor hybrid edges (or hybrid nodes at the tips in an extended newick string) do not need to have the edge weights associated with them, as the nodes which they connects are defined otherwise. In fact edge weights could be potential incompatible (and with rounding error often will), as this little example highlights: 
1. All (compatible) edge weights provided (works fine): 
```
net1 = readTopology("((a:2,(b:1)#H1:1):1,(#H1:0,c:1):2);") 
plot(net1, useEdgeLength=true) 
```
2. Plots fine but triggers warning message, which seems unnecessary in this case as the edge length is actually ignored (and not 1.0)
```
net2 = readTopology("((a:2,(b:1)#H1:1):1,(#H1,c:1):2);")
plot(net2, useEdgeLength=true) 
At least one non-missing edge length: plotting any NA length as 1.0
```
3. Plots ignores one of the edge weights #H1:20. This should trigger
warning instead as edge weights are incompatible: 
```
net3 = readTopology("((a:2,(b:1)#H1:1):1,(#H1:20,c:1):2);") 
plot(net3, useEdgeLength=true)
```

Cheers, 
Klaus

**Comment by cecileane** [comment]
Thank you Klaus! These weights are edge lengths, the way they are coded in your examples, in the parenthetical description. For each edge, the format is this: `:length` or `:length:support_value`, or this: `:length:support:inheritance_probability`. Any of these can be missing if unknown. For example, a minor hybrid edge with inheritance γ=0.05 whose length (substitutions/site) is unknown and whose bootstrap support is unknown would be coded like this: `::0.05`.

I am not exactly sure what you mean by "edge weight", I assumed that you meant inheritance probability, because you mention incompatible weight (and γ1 + γ2 should be 1.0 for hybrid edges 1 & 2 associated with the same hybrid node). I agree that all edges do not need to have an inheritance value associated with them, but we have a data structure for an edge, so all instances of this Edge type have a "gamma" field, even tree edges. Re-working the data structure for edges and nodes and networks would be quite extensive at this point... But the function `readTopologyLevel1` does check that γ1 + γ2 ≈ 1.0 for each pair of hybrid edges. We are also planning to add this check (and other checks) to the more generic function `readTopology`.

About your examples, more specifically:

2. In this example, `useEdgeLength=true` asks to draw edge lengths proportional to their actual length but one edge does not have a length. Hence the warning.
3. In the tree description, `#H1:20` means that one of the 2 hybrid edges associated with hybrid node H1 has length 20, which is plausible. Here 20 is not an inheritance value, so no problem. As an aside, it is possible for a minor hybrid edge to have a >0 length, in case the associated parental population went extinct, or in case none of its descendants are sampled in the study.

By the way, the plot function can now use R, through the `RCall` package (not yet in the documentation). It's faster and you can add stuff afterwards like you would using R:
```
plot(net1, :RCall, useEdgeLength=true)
```

**Comment by KlausVigo** [comment]
Hi @cecileane,  

thanks for the clarification now I understand. Most of the examples I saw missed the support values, so it was always ::0.05 and I got confused. Sorry about that.  

I am not exactly sure what you mean by "edge weight", 
edge weights should be edge lengths (Mike Hendy was always talking about weighted graphs). 

To 2 (and 3 it was only about plotting).
If you have a tree the number of nodes is the number of edges + 1. However if one adds hybridizations the number of edges is greater or equal then the number of nodes. 

Let look at this simple network and first plot it as a tree
```
net_as_tree =  readTopology("((SP_1:2,(SP_12:1)H1:1)A:1,(H1:5,SP_2:2)B:1);");  
plot(net_as_tree, useEdgeLength=true, showIntNodeLabel=true)
```
The distance from the root to the hybrid node H1 via A is 2, but is 6 if you go via B.  

If we plot the network it will depend on where we attach the hybrid species.  
Lets plot the network:
```
net1 =  readTopology("((SP_1:2,(SP_12:1)#H1:1)A:1,(#H1:5,SP_2:2)B:1);");  
plot(net1, useEdgeLength=true, showIntNodeLabel=true)
```
The edge length d(B, #H1) = 5 is ignored and set to 1, but it could have been missing.
```
net1_missing =  readTopology("((SP_1:2,(SP_12:1)#H1:1)A:1,(#H1,SP_2:2)B:1);");  
plot(net1_missing, useEdgeLength=true, showIntNodeLabel=true)
At least one non-missing edge length: plotting any NA length as 1.0
```
Identical plot, but warning

If we would add the hybrid species on the other #H1 node we get a different looking graph. 
```
net2 =  readTopology("((SP_1:2,#H1:1)A:1,((SP_12:1)#H1:5,SP_2:2)B:1);"); 
plot(net2, useEdgeLength=true, showIntNodeLabel=true)
```
Now the other edge is ignored and could be missing:
```
net2_missing =  readTopology("((SP_1:2,#H1)A:1,((SP_12:1)#H1:5,SP_2:2)B:1);"); 
plot(net2_missing, useEdgeLength=true, showIntNodeLabel=true)
At least one non-missing edge length: plotting any NA length as 1.0
```
The warning is actually misleading as NA length is set to 5 in this case and not needed in this case. 

Missing one of the edge lengths would actually ensure that there is a unique way to represent the network and the number of nodes is also the number of edges + 1 like in the tree. 

Klaus

**Comment by crsl4** [comment]
Thanks Klaus!
These are all good points. It would be nice to have a unique plot to represent a network, indeed. But one thing that might make it difficult is that we assume that the hybrid edge attach to the leaf node H1 is the minor hybrid edge, and is therefore plotted "horizontally", whereas the hybrid edge attached to the internal node H1 is supposed to be the major hybrid edge (part of the backbone tree) and is therefore plotted vertically. This is an assumption that we found in the description of the extended Newick format.
If we do not know the values of the inheritance probabilities, then we don't really know which hybrid edge is minor and which one is major, and we can plot the networks either way (like in your `net1` and `net2`). Without the inheritance probabilities, we treat the hybrid edge attached to a leaf as the minor hybrid edge. So, if we rewrite the parenthetical formal, we get different plots.

If we had inheritance probabilities, then we use those values to decide which hybrid edge is minor and which one is major.
For example:
```
net2_gamma =  readTopology("((SP_1:2,#H1:::0.9)A:1,((SP_12:1)#H1:5::0.1,SP_2:2)B:1);")
plot(net2_gamma, useEdgeLength=true, showIntNodeLabel=true, showGamma=true)
```
The plot matches what we had with `net1`.

**Comment by cecileane** [comment]
Agreed! The various paths from one node (the root, say) to a descendant node (H1, say) might not all have the same length.
- if edge lengths are proportional to time, then going from the root to H1 should always take the same length total, for all different paths (regardless of whether we go through A or through B)
-  but if branch lengths are in substitutions per site, or in coalescent units, then there is no theoretical reason for these paths to have the same lengths.

In the second case, I don't know how to represent all of the path lengths faithfully in a single plot, other than by annotating edges with their lengths (written as numbers!). But it's a concern that we should let users know about: with a warning message perhaps, like "beware, your network is not 'ultrametric', so edge lengths cannot all be drawn proportional to their length"?
