### ISSUE TITLE
RCall cluster issues

### ISSUE THREAD

**Issue by crsl4** [crsl4/PhyloNetworks.jl#67]
Hello,
There are many problems with installing RCall in clusters (see [here](https://github.com/JuliaInterop/RCall.jl/issues/198) and [here](https://github.com/JuliaInterop/RCall.jl/blob/master/docs/src/installation.md)). Apparently, some of these problems are fixed with RCall version 0.9 (I have not tested this myself, but IT people told me), but we still require RCall 0.6.1 in REQUIRE.
@cecileane @kwsparks is there any reason to restrict to this version of RCall, or can we try with version 0.9 and see if this solves issues for people?
Thanks!
Claudia

**Comment by crsl4** [comment]
Actually, the IT people have made it work with RCall 0.8.1.
They had to re-install R in a specific way, but I do not have the details. I have asked and waiting for a response. I'll let you know if I have more information, thanks!

**Comment by crsl4** [comment]
A bit more info: I need to do `export LD_LIBRARY_PATH=`R RHOME`/lib` before opening julia in the cluster, and according to the IT people you need to have "correct permissions on the R library files", whatever that means.
I am able to run in a cluster now, but I do not have enough information on what the IT people did in the background, sorry! I am using RCall 0.8.1, and I suspect now that the issue has nothing to do with the RCall version.

**Comment by cecileane** [comment]
Thank you for all this @crsl4 ! If you get the details of what they did to install R and RCall on your cluster (other than using v0.8.1 of RCall), that could be very useful for other users.

If you don't think it's about the RCall version, then we should not change our requirements. The Julia developers check that our requirements are minimal, when we register a new version. If our REQUIRE file says that we need RCall v0.8.1 and if we use RCall functions that have not changed / been introduced since RCall v0.6.1, then they ask us to downgrade our requirement to what's minimal --in that case v0.6.1.

And vice versa: it's happened that our REQUIRE file had an outdated requirement, that we had not noticed because we do `Pkg.update()` on a regular basis. So we might be using Foo v2.0, then start using in our package a new function from Foo v2.0 that was not in Foo v1.0, but forget to update our REQUIRE file from Foo 1.0 to Foo 2.0. When we register a new version, the Julia team checks that our requirements are correct, and minimal --which is really great. My point is that I would rather not bump up the RCall requirement if it's not necessary.

**Comment by crsl4** [comment]
I don't think that the solution is the RCall version, so I agree that we should leave REQUIRE as it is.
In [this issue](https://github.com/JuliaInterop/RCall.jl/issues/198), they say that:
If anyone else comes across this problem, the solution was to rebuild the R installation with `--enable-R-shlib` and to add `$R_HOME/lib` to the `LD_LIBRARY_PATH`, which what is done with:
```
export LD_LIBRARY_PATH=`R RHOME`/lib 
```

So, I suspect this is the solution, but I never tested this myself.

**Comment by cecileane** [comment]
see great trouble-shooting tips on the [google group](https://groups.google.com/d/msg/phylonetworks-users/kUv20paoqO4/emg7tez3CAAJ).
