### ISSUE TITLE
PhyloNetwork install error

### ISSUE THREAD

**Issue by tangerzhang** [crsl4/PhyloNetworks.jl#68]
Hi, when I am trying to open PhyloNetwork by typing "using PhyloNetwork" in Julia environment. I got error like below:

julia> using PhyloNetworks
INFO: Precompiling module PhyloNetworks.
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /public1/home/coop_wg/.julia/v0.6/NullableArrays/src/operators.jl:99.
ERROR: LoadError: LoadError: Could not find R installation. Either set the "R_HOME" environmental variable, or ensure the R executable is available in "PATH".
Stacktrace:
 [1] locate_Rhome_libR() at /public1/home/coop_wg/.julia/v0.6/RCall/src/setup.jl:118
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /public1/home/coop_wg/.julia/v0.6/RCall/src/setup.jl, in expression starting on line 121
while loading /public1/home/coop_wg/.julia/v0.6/RCall/src/RCall.jl, in expression starting on line 41
ERROR: LoadError: Failed to precompile RCall to /public1/home/coop_wg/.julia/lib/v0.6/RCall.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /public1/home/coop_wg/.julia/v0.6/PhyloNetworks/src/PhyloNetworks.jl, in expression starting on line 14
ERROR: Failed to precompile PhyloNetworks to /public1/home/coop_wg/.julia/lib/v0.6/PhyloNetworks.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405

I have installed R-3.4.3 and pretty sure the R executable is available in my "PATH". I add the following information in the .bash_profile:
export R_HOME=/public1/home/coop_wg/software/R-3.4.3:$R_HOME
export LD_LIBRARY_PATH=$R_HOME/lib:$LD_LIBRARY_PATH
export PATH=$R_HOME/bin:$PATH

Could anyone help me out? How to solve the problem?
Thanks a lot!

**Comment by crsl4** [comment]
Sorry that you are having this issue. This is actually happening to many people (sadly). There is a [discussion in the google group](https://groups.google.com/forum/#!topic/phylonetworks-users/kUv20paoqO4).
I found two links that offer a solution: [here](https://github.com/JuliaInterop/RCall.jl/issues/198) and 
[here](https://github.com/JuliaInterop/RCall.jl/blob/master/docs/src/installation.md), but if you are using a cluster (instead of your personal computer), you might not have root permissions to re-install R.
Since we only use R to enhance our plotting capabilities, we are working on separating the plotting functions (that use RCall) from the core PhyloNetworks package, so that people don't need to struggle with the R-julia compatibility in a cluster. I cannot offer a solution right now, but we are working on this!

**Comment by crsl4** [comment]
A bit more info: In my case, the permissions on the R library file were incorrect. In the location where R is installed, find the file called libR.so (e.g. /path/to/R/lib64/R/lib) and make sure it has
755 perms.

**Comment by tangerzhang** [comment]
Problem solved! Thanks!
