### ISSUE TITLE
add example in manual: when the root conflicts with the direction of estimated reticulation

### ISSUE THREAD

**Issue by tangerzhang** [crsl4/PhyloNetworks.jl#75]
Hi I am re-root a snag tree, but see error below:
julia> snaqtree4 = rootatnode!(net4, "Outgroup")
INFO: node 24 is a leaf. Will create a new node if needed, to set taxon "Outgroup" as outgroup.
RootMismatch: non-leaf node 14 had 0 children.
Could be a hybrid whose parents' direction conflicts with the root.
isChild1 and containRoot were updated for a subset of edges in the network only.
Reverting to old root position.
ERROR: RootMismatch: non-leaf node 14 had 0 children.
Could be a hybrid whose parents' direction conflicts with the root.
isChild1 and containRoot were updated for a subset of edges in the network only.

Is there anything I can do to solve this problem?
Thanks!

**Comment by cecileane** [comment]
The `rootatnode!` function is telling you that your desired root position conflicts with one (or more) of the reticulations. Each reticulation gives information about directionality: the hybrid node has to be younger (or of the same age) as both of its parents, so time has to flow "downwards" of that hybrid node. The root cannot be "below" any hybrid node. The error you got means that the desired root position is "below" one (or more) hybrid nodes: there is a time conflict.

If you are sure about your outgroup and about your root position, then it means that one inferred reticulation is incorrect. Its placement might be correct, but its direction would be incorrect. If you got your network via `snaq!` then you can check the `.networks` output file: it should have a number of networks that are slight modifications of the best network, where the modifications changed the direction of one reticulation at a time. For each modified network, you should have its score. So if you see a modified network that has a score that's not too far from the best network, and that can be re-rooted with your known root position, then it is a better candidate than the network with the best score.

@crsl4: in the manual, we should add an simple example showing this issue, with pictures of why there is a time conflict, and how to read networks in the `.networks` file, and how to re-root them and how to see if their scores is not "too" bad. For example, if we are looking at networks with 2 reticulations, we would be looking for a large drop in the score from 0 to 1 to 2 reticulations, but a small difference in score between the best and the modified network at h=2 reticulations, relative to the drop from  1 to 2 reticulations. I will update the title of the issue to reflect the need for a manual page on how to do this.

**Comment by crsl4** [comment]
Yes, this is a good idea. Do you think that we can put this in the "Network comparison and manipulation"?

**Comment by cecileane** [comment]
One aspect is specific to `snaq!` (looking at the results in the `networks` file, drop in score, etc.), so I would put those aspects in the [candidate networks](http://crsl4.github.io/PhyloNetworks.jl/latest/man/fixednetworkoptim/) section, and perhaps rename that section. In the [re-rooting](http://crsl4.github.io/PhyloNetworks.jl/latest/man/dist_reroot/#re-rooting-trees-and-networks) subsection, we could explain that the "re-root mismatch" error is an error due to a time conflict, and show figures to explain how a reticulation gives partial time information. I can imagine such conflicts in many situations other than using `snaq!`. For situations when they occur after `snaq!`, we could point to the new subsection to be added to [candidate networks](http://crsl4.github.io/PhyloNetworks.jl/latest/man/fixednetworkoptim/), where there would be suggestions on how to deal with this timing conflict.

**Comment by cecileane** [comment]
fixed with 7ffa848d8317b5ed1c5d2955b6b64b468cb481f3
